baseURL = "https://racsofeob2.github.io/"
languageCode = "es-es"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "// 0xRac Blog"

[pagination]
pagerSize = 3

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
 
[params]
  google_analytics_id = ""

  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true # the description below the title on home page
  showPostsOnHomepage = false
  showReadTimeOnPosts = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = false
  # OLD CORRECTS, OVERWRITTEN IN THE CUSTOM.CSS FILE
  # ---------
  # highlightColor = '#7b16ff'
  # baseColor = "#ffffff"
  # baseOffsetColor = "#eaeaea"
  # headingColor = "#1c1b1d"
  # textColor = "#4e5157"
  # dotColor = "#7b16ff"
  # ---------
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;700&family=Ubuntu+Mono:wght@400;700&display=swap"
  fontFamilyHeading = "Ubuntu"
  fontFamilyParagraph = "Ubuntu"
  fontFamilyMonospace = "Ubuntu Mono"
  showAboutPage = false  # Toggle to control About page visibility
  github_username = "Racsofeob2"

  footer_text = ":: 0xRac Blog"  # Add this line for custom footer text
  footer_year = "2025-2026"  # Static year for footer

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "CTF"
    identifier = "CTF"
    weight = 3
    url = "/CTF/"

